apiVersion: v1
kind: Service
metadata:
  name: demo-app-lb
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80 # The port clients use to access the service
      targetPort: 5000 # The port your application is listening on in the pod
  type: LoadBalancer
